### ISSUE TITLE
Web IDE in Firefox

### ISSUE THREAD

**Issue by PhiLhoSoft** [ceylon/ceylon-web-ide-backend#81] opened 2015-10-16 10:40 UTC
Lastest Firefox: 41.0.1

- The selection is not visible. (I can see it in Chrome.)
- The Dark button changes the syntax highlighting but not the background.
- Also drag'n'drop of a line works... if I drop after the first char of the target line (or on an empty line). Nearer of the gutter, I get a cursor blinking between pointer and "not drop", and the drop is ignored.
- Actually, if I double-click a word and drag it, the cursor might be stable or blinking, depending on the drop position (no particular pattern, a same position can blink, and if I go back to it, it can be stable). If I drop when stable, it works: word is moved (copied with Ctrl). If I drop when blinking... Firefox attempts to go to www.<selectedword>.com!

Generic remark (also applies to Chrome): the IDE should detect the user navigates away from the page, and if the document is dirty, ask for confirmation.

**Comment by gavinking** [comment] 2015-10-16 13:31
> - The selection is not visible. (I can see it in Chrome.)
> - The Dark button changes the syntax highlighting but not the background.

I can't reproduce either of these problems in Firefox on Mac OS.

**Comment by gavinking** [comment] 2015-10-16 13:32
Nor do I observe anything weird with drag+drop.

**Comment by PhiLhoSoft** [comment] 2015-10-16 15:22
Sorry, I should have mentioned I see this on Windows 7 Professional.
I just upgraded to v.41.0.2, with same behavior.

**Comment by quintesse** [comment] 2015-10-16 15:46
Just tried with 41.0.1 on Windows 7 Home Premium and things work just fine.
Can't it be some plugin you installed maybe?

**Comment by lucaswerkmeister** [comment] 2015-10-16 16:17
I get different results (Firefox 43.0a2 (2015-10-14), Arch Linux):

- The selection is visible, but in Dark mode pretty bright, making the text almost unreadable.
- Dark changes syntax highlighting (though the changed highlighting for Markdown renders the `[]` part of links almost unreadable) and background, but not the rest of the page (which still has some bright elements).
- Drag and drop doesn’t work at all. The selection color changes from blue-ish to grey-ish, but the cursor remains the same, and nothing happens.

> Generic remark (also applies to Chrome): the IDE should detect the user navigates away from the page, and if the document is dirty, ask for confirmation.

+1. That would be an [`beforeunload`](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event handler.

**Comment by PhiLhoSoft** [comment] 2015-10-16 16:26
Oops! I totally forgot I had a Stylish style to fix dark theme code snippets on Ceylon-lang.org, which applies here too...
Deactivating it restores the selection and the dark theme.
I still have issues with drag'n'drop, I will check if deactivating all the extensions fixes that.
Sorry for the noise.

**Comment by gavinking** [comment] 2015-10-17 12:11
Closing.

**Closed by gavinking** 2015-10-17 12:11 UTC
